### ISSUE TITLE
vuejs + clojurescript 

### ISSUE THREAD

**Issue by xingzhefeng** [reagent-project/reagent#328] opened 2017-12-03 15:51 UTC
Is there a plan to support vuejs  with  clojurescript  ? I hope it can be realized
https://github.com/Gonzih/glue  [https://github.com/Gonzih/glue](A gentleman is trying.)

**Comment by danielcompton** [comment] 2017-12-03 21:07
Dupe of #271.

**Closed** 2017-12-04 13:43 UTC
