### ISSUE TITLE
Missing symbols when fast typing in IE (Internet Explorer)

### ISSUE THREAD

**Issue by ai212983** [reagent-project/reagent#253] opened 2016-07-13 14:39 UTC
Reproduced on IE11, Win8.

https://reagent-project.github.io/ - when fast typing in input field ("The value is now: foo" example), some symbols will be missing. There's no such problem with [pure react form](http://ruanyf.github.io/react-demos/demo09/). Replacing `:value` with `:defaultValue` fixes the problem, so problem is only with controlled inputs.

**Comment by ducky427** [comment] 2016-07-13 15:08
@ai212983, I tried on my windows 8 machine and IE11 and I couldn't reproduce the issue. Can you consistently reproduce the issue and if so, could you post a video of it or something?

**Comment by ducky427** [comment] 2016-07-13 15:10
Additionally what version of React are you testing against?

**Comment by ai212983** [comment] 2016-07-13 15:14
@ducky427: You have to type **really** fast. Try to type "test" very fast on https://reagent-project.github.io/ page. Reproducible pretty much every time, if you're typing fast enough.

React version is 15.1.0, according to page sources. (yes, i know they've fixed some IE input issues in v.15).

I'll record video a bit later, got no proper tools on my Windows notebook.

**Comment by ai212983** [comment] 2016-07-13 15:29
@ducky427 Okay, here's [mp4 on dropbox](https://www.dropbox.com/s/2yrsaqtjvucbswr/reagent-issue-253.mp4?dl=0). I'm typing "test" first on reagent home page, then on pure react form demo. In reagent demo page you can see a missing character briefly blinking and disappearing.

**Comment by ducky427** [comment] 2016-07-13 15:29
@ai212983, you are right. I can also reproduce this issue on IE8 on Win8. It works on Chrome 51 on Win8.

**Comment by ai212983** [comment] 2016-07-13 15:32
@ducky427 AFAIK, IE8 is no more officially supported. This video was made with IE11/Win8. Having this bug in IE11 is... well, a bit more troubling than in IE8. 

Edge works fine though.

**Comment by ducky427** [comment] 2016-07-13 15:33
I am sorry. I meant IE11.

**Comment by antishok** [comment] 2016-07-13 16:14
Reproduced also on IE11 on Win7. You don't even have to type fast, just normally

**Comment by holmsand** [comment] 2016-07-13 19:17
Seems that IE doesn't report change events like other browsers. I'm looking for a workaround...

**Comment by holmsand** [comment] 2016-07-14 08:07
I think I've found a solution: turns out that IE doesn't report change events on every input modification, but just sort of once in a while. That makes the actual value and the value Reagent assumed it had get out of sync, causing lost keystrokes.

I've pushed what I hope is a fix to https://reagent-project.github.io and a new snapshot to clojars (i.e 0.6.0-SNAPSHOT).

Since the logic for input updates has changed quite a bit, I'd really appreciate if you could try it out.

**Comment by ai212983** [comment] 2016-07-14 08:25
@holmsand Thanks, Dan,  will do so later today.

**Comment by ai212983** [comment] 2016-07-14 08:29
@holmsand Works fine to me, greatly appreciated!

**Comment by ducky427** [comment] 2016-07-14 08:57
thanks a lot @holmsand. works for me as well!

**Comment by Deraen** [comment] 2016-07-14 16:36
Super!

Tested this with my component library and this has fixed the problems with IE!

Didn't notice any new problems with IE or Chrome.

**Comment by Deraen** [comment] 2017-03-11 00:01
This was fixed in 0.6.0

**Closed by Deraen** 2017-03-11 00:01 UTC
