### ISSUE TITLE
Text cursor jumps to last position for `[:input]` fields

### ISSUE THREAD

**Issue by jonase** [reagent-project/reagent#79] opened 2014-12-14 13:57 UTC
The following minimal example

```clojure
(defn my-input [on-change text]
  [:div [:input {:type "text"
                 :value (.toUpperCase text)
                 :on-change #(on-change (-> % .-target .-value))}]])

(def text (reagent/atom "foo"))

(defn main-page []
  [my-input #(reset! text %) @text])
```

will cause the cursor to jump to the last position after each key stroke (try to insert a character in the middle of the string). If I replace `(.toUpperCase text)` with `text` the cursor stays at the correct position.

**Comment by dmohs** [comment] 2015-01-21 03:53
This might be one of those cases where doing the right thing, UI-wise, is tough. I don't think you can modify the event, so your only option might be to check the character on keypress and, if it is lowercase, prevent the event and fire a new keypress event with the uppercase character instead. I'm not certain that would work, but I think it has a chance.

In any case, if this is a bug, it is a bug in React or the browser. I think it's important for Reagent to remain bug-for-bug compatible with React to the extent possible, so I would recommend closing this issue.

**Closed** 2015-02-02 20:09 UTC

**Comment by gtrak** [comment] 2015-02-02 20:12
Similar issue in Om for reference: https://github.com/swannodette/om/issues/295

**Comment by mike-thompson-day8** [comment] 2015-05-08 02:02
> Keeping the cursor in the "right" place generally would be quite tricky

It was :-) but #26 seems to work perfectly in all the corner cases tested.

**Comment by marcloyal3** [comment] 2015-05-09 05:15
@mike-thompson-day8 CC: @yogthos 

Mike, 

Please articulate why you think @holmsand is wrong in his statement that:

"Reagent behaves just like \"normal\" React in this regard – both Reagent and React just set the value of the input field to the specified value, and leaves it up to the browser to decide where the cursor should go."

Also, your solution hard codes the HTMLElement tags, which is problematic with respect to the new feature in web browsers known as "Custom Elements" a la  Document.registerElement() 

Marc

**Comment by mike-thompson-day8** [comment] 2015-05-09 05:25
@marcloyal  Eh?  Dan is 100% right. That *is* indeed what causes this problem.  The proposed patch FIXES that problem.

**Comment by marcloyal3** [comment] 2015-05-11 19:24
You can also use "text-transform: uppercase" for this particular case. In other words, this case is fixable with CSS.

I have a working example I'll post on the github issue

**Comment by yogthos** [comment] 2015-05-11 22:53
I think if the issue is addressed by CSS then that would be the preferred method in any case as it's not a good practice to bake styling into content.
