### ISSUE TITLE
Rendering of unescapeEntities fails with render-to-static-markup (nodejs)

### ISSUE THREAD

**Issue by au-phiware** [reagent-project/reagent#326] opened 2017-11-23 02:55 UTC
I'm not sure if this is a failure of reagent or react, but I'm hoping you can let me know.

I created a [gist](https://gist.github.com/au-phiware/d2b9cba46f7f60cd1a76e9e94d94f23c):

## Steps to reproduce

0. `git clone https://gist.github.com/d2b9cba46f7f60cd1a76e9e94d94f23c.git`
1. Copy/symlink `cljs.jar` (as per [Quick Start](https://clojurescript.org/guides/quick-start)) and `reagent-0.8.0-alpha2.jar` in the project directory..
2. Execute `make`.

## Expected outcome

```
<p><i>Does not work: &amp;nbsp;</i>
<i>       Does work: &nbsp;</i>
<i>     Should work: &nbsp;</i></p>
```

## Actual outcome

```
<p><i>Does not work: &amp;nbsp;</i>
<i>       Does work: &nbsp;</i>
<i>     Should work: &amp;nbsp;</i></p>
```

`test.cljs`:
```
(ns test.core
  (:require
    [cljs.nodejs :as nodejs]
    [goog.string :refer [unescapeEntities]]
    [reagent.dom.server :as dom]))

(nodejs/enable-util-print!)

(print
  (dom/render-to-static-markup
    [:p
     [:i "Does not work: " "&nbsp;"] "\n"
     [:i {:dangerouslySetInnerHTML {:__html "       Does work: &nbsp;"}}] "\n"
     [:i "     Should work: " (unescapeEntities "&nbsp;")]]))
```

`build.clj`:
```
(require 'cljs.build.api)

(cljs.build.api/build
  "."
  {:main 'test.core
   :output-to "main.js"
   :target :nodejs
   :install-deps true
   :npm-deps
   {:react "15.6.2"
    :react-dom "15.6.2"
    :create-react-class "15.6.2"}})
```

`Makefile`:
```
.PHONY: run

run: main.js
	node main.js

main.js: reagent-0.8.0-alpha2.jar cljs.jar build.clj test.cljs
	java -cp cljs.jar:reagent-0.8.0-alpha2.jar:test.cljs clojure.main build.clj

reagent-0.8.0-alpha2.jar: ~/.m2/repository/reagent/reagent/0.8.0-alpha2/reagent-0.8.0-alpha2.jar
	ln -s ~/.m2/repository/reagent/reagent/0.8.0-alpha2/reagent-0.8.0-alpha2.jar
```

**Comment by Deraen** [comment] 2017-11-23 06:58
It does work for me, add I added test case for this: https://github.com/reagent-project/reagent/commit/4dcd82a28e8ff848ba1360e14420b508a70301df
https://circleci.com/gh/reagent-project/reagent/138

Not sure what could cause the problem for you. CI runs tests with Node deps also.

**Comment by Deraen** [comment] 2017-11-23 07:55
Try validating what `(unescapeEntities "&nbsp;")` returns, with console.log or something.

**Comment by au-phiware** [comment] 2017-11-23 14:20
I added a Dockerfile:

```
FROM pgoudreau/docker-maven-node

CMD make
WORKDIR /usr/src/app

RUN apk add --virtual .build-dependencies --update wget ca-certificates bash \
 && wget -q "https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein" \
    -O /usr/local/bin/lein \
 && chmod 0755 /usr/local/bin/lein \
 && git clone --shallow-since=2016-05-28T22:57:31Z https://github.com/clojure/clojurescript.git /usr/src/clojurescript \
 && cd /usr/src/clojurescript \
 && script/uberjar \
 && cp target/cljs.jar /usr/src/app \
 && git clone --depth 1 https://github.com/reagent-project/reagent.git /usr/src/reagent \
 && cd /usr/src/reagent \
 && lein install \
 && cp target/reagent-0.8.0-alpha2.jar /usr/src/app \
 && cd /usr/src/app \
 && rm -rf /usr/src/clojurescript /usr/src/reagent /usr/local/bin/lein /root/.* || true \
 && apk del .build-dependencies \
 && apk add make

COPY . /usr/src/app
```

And it still fails, so it can't just be me, right?

I added a repl to the Makefile and tried your suggestion:

```
$ docker run -it reagent-html-entity make repl                                                         
java -cp cljs.jar:reagent-0.8.0-alpha2.jar clojure.main -e "(require 'cljs.repl 'cljs.repl.node) (cljs.repl/repl (cljs.repl.node/repl-env))"
ClojureScript Node.js REPL server listening on 57979
To quit, type: :cljs/quit
cljs.user=> (require 'goog.string)
nil
cljs.user=> (goog.string/unescapeEntities "&nbsp;")
"&nbsp;"
cljs.user=>
```

I'm guessing that the string is supposed to be wrapped in some object that marks it as raw HTML?

**Comment by au-phiware** [comment] 2017-11-23 14:30
I've pushed the image I built to docker hub: https://hub.docker.com/r/phiware/reagent-html-entity/

**Comment by au-phiware** [comment] 2017-11-23 14:51
I've just had a look at your test, I didn't realise that unescapeEntities is supposed to emit the raw unicode characters. I'm definitely not seeing that happen... I think it's a result of this line: https://github.com/google/closure-library/blob/master/closure/goog/string/string.js#L707

From the repl, `goog.global.document` doesn't appear to exist:

```
cljs.user=> (import '[goog.global])
nil
cljs.user=> goog.global.document
nil
cljs.user=>
```

Does your test rig mock that out?

**Comment by au-phiware** [comment] 2017-11-23 14:55
This is what happens if I try to fudge it:

```
cljs.user=> (aset goog.global "document" #js {})
#js {}
cljs.user=> (goog.string/unescapeEntities "&nbsp;")
TypeError: goog.global.document.createElement is not a function
    at Object.goog.string.unescapeEntitiesUsingDom_ (/usr/src/app/.cljs_node_repl/goog/string/string.js:748:32)
    at Object.goog.string.unescapeEntities (/usr/src/app/.cljs_node_repl/goog/string/string.js:706:26)
    at repl:1:91
    at repl:9:3
    at repl:14:4
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.exports.runInThisContext (vm.js:77:17)
    at Domain.<anonymous> ([stdin]:50:34)
    at Domain.run (domain.js:221:14)
    at Socket.<anonymous> ([stdin]:49:25)
```

**Comment by au-phiware** [comment] 2017-11-26 22:34
I tried adding `jsdom-global` and it works as expected:

```
$ make repl                                            
java -cp cljs.jar:reagent-0.8.0-alpha2.jar clojure.main -e "(require 'cljs.repl 'cljs.repl.node) (cljs.repl/repl (cljs.repl.node/repl-env))"
ClojureScript Node.js REPL server listening on 52308
To quit, type: :cljs/quit
cljs.user=> (import '[goog.global])
nil
cljs.user=> (require '[jsdom-global :as jsdom])
nil
cljs.user=> (goog.string/unescapeEntities "&nbsp;")
"&nbsp;"
cljs.user=> (jsdom)
#object[cleanup]
cljs.user=> (goog.string/unescapeEntities "&nbsp;")
" "
cljs.user=> 
```

So, this seems to be expected behaviour from `goog.string/unescapeEntities`, but I would suggest that your test case is not quite right since it relies on something that's outside of reagent (or its dependencies).

I added a note on the wiki where I first encountered this technique: https://github.com/Day8/re-frame/wiki/More-advanced-Reagent-techniques.

**Comment by au-phiware** [comment] 2017-11-26 22:36
BTW, I've been pushing updates to the gist, so all the code blocks in my comments should be reproducible.

**Comment by Deraen** [comment] 2017-11-28 14:05
Hmm, I'm still trying to understand why this works on Node for me. I'm quite sure I'm not including any DOM implementations for test env.

The Closure should check if DOM is available, and if not, use slower implementation which doesn't require DOM: https://github.com/google/closure-library/blob/master/closure/goog/string/string.js#L711

So `(aset goog.global "document" #js {})` will break this because Closure will think DOM is available.

**Comment by Deraen** [comment] 2017-11-28 14:08
And yes, I can reproduce the problem with your examples.

**Comment by Deraen** [comment] 2017-11-28 14:12
Oh right, Closure `unescapePureXmlEntities_` only supports a few named chars, not including `nbsp`... But why does this work for me...

**Comment by Deraen** [comment] 2017-11-28 14:21
Huh, I'm blind, the test doesn't pass on Node:

```
FAIL in (html-entities) (cljs/test.js:431:14)
expected: (= "<i> </i>" (server/render-to-static-markup [:i (gstr/unescapeEntities "&nbsp;")]))
  actual: (not (= "<i> </i>" "<i>&amp;nbsp;</i>"))
```

The test runner just doesn't set exit code correctly.

**Comment by Deraen** [comment] 2017-11-28 15:24
I have now fixed Node tests to property report status, it was broken because an async test case required DOM, for some reason no error was ever reported from this. Maybe I'd need to call `done` fn on some `catch` (https://github.com/reagent-project/reagent/commit/7a3bc4c21281795b98ec097796dccc7bd9e8da0a).
I have updated the entity test to check that numeric entities work always, and test named entity only if DOM is available: https://github.com/reagent-project/reagent/commit/6eb9f4f6fb25ac81a4eaa93789757a6181119ac9

I think on Reagent side there isn't more I can do, if you need to use this on Node, you need find another unescape implementation, create your own or maybe use numeric entities or just write unicode char in the code (https://en.wikipedia.org/wiki/Non-breaking_space#Keyboard_entry_methods; I guess I'm lucky that my Finnish layout includes this by default)

**Closed** 2017-11-28 15:35 UTC
