### ISSUE TITLE
Fatal regex-related exception in Firefox

### ISSUE THREAD

**Issue by polymeris** [reagent-project/reagent#148] opened 2015-06-23 19:41 UTC
Wanted to try the live demo, but got this error in the JS console:
`uncaught exception: Invalid match arg: /^\//`

Might be this issue: https://github.com/clojure/clojurescript/commit/d717b4edea074fcfd3e718a6134238ba26f76f82

**Comment by mike-thompson-day8** [comment] 2015-06-29 04:20
So the test is this:   if you switch to a recent version of clojurescript and the problem disappears, then it was that bug (now fixed), which means the entire issue disappears. 

I ran into the same issue myself, and the problem disappeared when I went to a new version of cljs:
https://bugzilla.mozilla.org/show_bug.cgi?id=1149604

**Comment by mike-thompson-day8** [comment] 2015-06-29 04:28
Sorry, I misread your issue.  I can see now you are simply warning that the live demo page has this problem on firefox.

The solution is for Reagent's live demo  to be re-compiled  with a more recent version of cljs, and then re-deployed.  I don't have permissions to do this, so we'll have to wait for one of the 4 maintainers. 

The workaround is:  use a different browser for the moment (problem is firefox specific).

**Comment by gadfly361** [comment] 2015-06-29 17:19
I think we should add @mike-thompson-day8 to the Reagent Project org. What do you think: @holmsand @yogthos @seancorfield @Whoops @Frozenlock

**Comment by yogthos** [comment] 2015-06-29 17:25
I think it's a great idea, Mike has been contributing actively and helping out with issues and pull requests for a while now.

**Comment by Whoops** [comment] 2015-06-29 18:59
agreed

**Comment by Whoops** [comment] 2015-06-29 19:09
Also are we talking about http://reagent-project.github.io/? I just tested all the widgets on the page in Firefox 38.0.5 on OSX and everything appeared fine.

**Comment by seancorfield** [comment] 2015-06-29 22:48
:+1:

**Comment by mike-thompson-day8** [comment] 2015-06-29 23:27
Okay, thanks, let's see what Dan says about commit rights.  

In the meantime,  I can confirm what @Whoops found:  the demo page works fine with the newly released firefox 38.0.5.  So the problem only shows with the right combination of (1) a certain version of firefox and (2) prior to a certain version of clojurescript.  

Given the new version of Firefox out there now, we can probably close this.

**Comment by yogthos** [comment] 2015-06-29 23:31
Agreed, since firefox does autoupdates, I don't think there's much value supporting older versions, especially if it only happens with certain versions of cljs as well.

**Closed by yogthos** 2015-06-29 23:31 UTC

**Comment by yogthos** [comment] 2015-07-04 17:27
@holmsand any chance you could weigh on this :)
