### ISSUE TITLE
Range/Slider component doesn't fire onChange at midpoint 

### ISSUE THREAD

**Issue by BrianLitwin** [reagent-project/reagent#448] opened 2019-09-05 20:15 UTC
If you create this component: 

```cljs

[:input 
:type "range" 
:min 0 
:max 100 
:step 25 
:value 0 
:onInput #(prn "onInput") 
:onChange #(prn "onChange")}]

```

When the component first initializes, if you click on the components midpoint such that the value is 50, the `onInput` will fire but `onChange` will not, and the slider will move to the midpoint. After the first click, `onChange` fires as it should. 

The use case where this arose was trying to update `value` on `onChange`, and `value` not updating if the user's first move after the component initialized was to click on the middle of the slider.

**Comment by Deraen** [comment] 2020-04-19 11:59
Can't reproduce or not enough information. I tested on current master branch.

I added the current value to print calls, and I can see when I click on the middle point, both events fire with value 50. And the slider doesn't move, as it should as the value is always 0.

Closing this for now, but if you can reproduce and provide more information I'll open this again.

**Closed by Deraen** 2020-04-19 11:59 UTC
