### ISSUE TITLE
Assoc'ing multiple values into a cursor is broken in 0.4.3

### ISSUE THREAD

**Issue by rsslldnphy** [reagent-project/reagent#95] opened 2015-02-04 15:43 UTC
Hi, just noticed this strange behaviour of assoc used with a cursor, probably best illustrated by a code snippet:

```clojure
ClojureScript:example.core> (def a (atom {}))
#<Atom: {}>
ClojureScript:example.core> (swap! a assoc :a 2 :b 3)
{:a 2, :b 3}
ClojureScript:example.core> (require '[reagent.core :as r])
ClojureScript:example.core> (def r (r/atom {}))
#<Atom: {}>
ClojureScript:example.core> (def rc (r/cursor [:x] r))
#<Cursor: [:x] #<Atom: {}>>
ClojureScript:example.core> (swap! rc assoc :y 3 :z 4)
{:x {:y 3, (:z 4) nil}} ;; shouldn't this be {:x {:y 3 :z 4}}?
```

**Comment by mike-thompson-day8** [comment] 2015-02-05 03:43
By version:
 - I confirmed reported (incorrect) results in 0.4.3
 - I tested 0.5.0-alpha  and it worked correctly
 - i tested 0.5.0-alpha2 and had a different kind of outcome as follows:

```
ClojureScript:cljs.user> (require '[reagent.core :as r])

ClojureScript:cljs.user> (def r (r/atom {}))
#<Atom: {}>
ClojureScript:cljs.user> (def rc (r/cursor [:x] r))
#<Cursor: [:x] nil>                                       ;;   <--   notice the `nil`
ClojureScript:cljs.user> (swap! rc assoc :y 3 :z 4)
{:y 3, :z 4}
```

**Comment by holmsand** [comment] 2015-02-05 07:29
@mike-thompson-day8 I think the behaviour in 0.5.0-alpha2 is the correct one…

After the swap, `r` becomes `{:x {:y 3, :z 4}}`, and `rc` consequently `{:y 3, :z 4}`. I.e: the `swap!` on the cursor returns the same value as `(swap! (atom nil) assoc :y 3 :z 4)` would.

**Comment by mike-thompson-day8** [comment] 2015-02-05 07:50
@holmsand   quite right!  The value in `rc` is what's printed, not `r`. Silly of me.

So, 0.5.0 is correct, but there's an issue with 0.4.3.

**Comment by holmsand** [comment] 2015-02-09 18:18
Closing this, since it seems to be ok in 0.5.0.

**Closed by holmsand** 2015-02-09 18:18 UTC
