### ISSUE TITLE
Test of should-component-update FAILS (code included)

### ISSUE THREAD

**Issue by marcloyal3** [reagent-project/reagent#113] opened 2015-03-16 23:06 UTC
@holmsand 

As you can see, the app-state ratom is getting updated 5 seconds after rendering, and it is dereferenced in the component function but should-component-update is never getting called.

Please open Chrome dev tools (or Firebug) to see debug messages, and notice how the update only results in will-update and did-update callbacks but not should-component-update.

```clojure
(ns main.core
  (:require [reagent.core :as r :refer [cursor]]))

(enable-console-print!)

(def app-state (r/atom {:form-data {:first "John"
                                   :last "Hook"
                                   :email "Hook@gmail.com"
                                   :password ""}
                      :errors {:first "Arrr! no first name!"
                               :last "Arrr! no last name!"
                               :email "Arrr! no email!"
                               :password "Arrr! weak password!"
                               }}))

(defn update-form-data! [form-data-cursor name event]
  (let [value (.-value (.-target event))]
    (swap! form-data-cursor assoc (keyword name) value)))

(defn lookup-error-message [errors-cursor field-name]
  (let [errors @errors-cursor
        field-error (errors (keyword field-name))]
    field-error))

(defn input-function [options]
  (let [form-data-cursor (options :form-data-cursor)
        errors-cursor (options :errors-cursor)
        field-name (options :name)
        value (@form-data-cursor (keyword field-name))
        with-value (assoc options :value value)
        with-on-change (assoc with-value :on-change #(update-form-data! form-data-cursor field-name %1))]
    [:div  [:input.reagent-input-component with-on-change]
     [:p (lookup-error-message errors-cursor field-name)]]))

(defn input-factory [form-data errors]
  (fn reusable-input [options]
    (let [options-with-data (assoc options :form-data-cursor form-data)
          options-with-errors (assoc options-with-data :errors-cursor errors)]
      (input-function options-with-errors)
      ))
  )

(defn input-component [data-cursor errors-cursor options]
  (let [
         input (input-factory data-cursor errors-cursor)
         lifecycle (fn [args]
                     (println "component is in" (args :phase) "phase"))
         ]
    (r/create-class
      {
        :get-initial-state #(lifecycle {:phase "'Get Initial State'" :this %1 :arg1 %2 :arg2 %3 :arg3 %4})
        :component-state-did-update #(lifecycle {:phase "'State Did Update'" :this %1 :arg1 %2 :arg2 %3 :arg3 %4})
        :component-will-mount #(lifecycle {:phase "'Will Mount'" :this %1 :arg1 %2 :arg2 %3 :arg3 %4})
        :component-did-mount #(lifecycle {:phase "'Did Mount'" :this %1 :arg1 %2 :arg2 %3 :arg3 %4})
        :component-will-receive-props #(lifecycle {:phase "'Will Receive Props'" :this %1 :arg1 %2 :arg2 %3 :arg3 %4})
        :should-component-update #(lifecycle {:phase "'Should Update'" :this %1 :arg1 %2 :arg2 %3 :arg3 %4})
        :component-will-update #(lifecycle {:phase "'Will Update'" :this %1 :arg1 %2 :arg2 %3 :arg3 %4})
        :component-did-update #(lifecycle {:phase "'Did Update'" :this %1 :arg1 %2 :arg2 %3 :arg3 %4})
        :component-will-unmount #(lifecycle {:phase "'Will Unmount'" :this %1 :arg1 %2 :arg2 %3 :arg3 %4})
        :reagent-render
        (fn [data-cursor errors-cursor options]
          [:div (str @app-state)
           [input options]])}
      )
    )
  )

(defn app-view []
  (let [data-cursor (cursor app-state [:form-data])
        errors-cursor (cursor app-state [:errors])
        ]
    (fn [] [:div
    [:form
     [input-component data-cursor errors-cursor {:name "first" :placeholder "First Name"}]
     [input-component data-cursor errors-cursor {:name "last" :placeholder "Last Name"}]
     [input-component data-cursor errors-cursor {:name "email" :placeholder "Email"}]
     [input-component data-cursor errors-cursor {:name "password" :placeholder "Password" :type "password"}]
     ]])
    ))

; render 

(r/render [app-view] (.getElementById js/document "app"))

; call update after 5 seconds

(defn update-atom []
  (swap! app-state assoc-in [:errors :first] "Yo Ho Ho!")
  )

(.setTimeout js/window update-atom 5000)

```

**Comment by marcloyal3** [comment] 2015-03-16 23:15
I'm pretty sure I can write another test where should-component-update does get called. However, I'm unsure why it's not getting called here given the view is getting updated. What am I missing?

**Comment by holmsand** [comment] 2015-03-17 10:33
That behavior is to be expected: `:should-component-update` is not called when a component is re-rendered because a deref'ed atom changed (unfortunately, perhaps). It is only called when a component receives new arguments from a parent.

The reason for this behavior is that it would add quite a bit more complexity in the implementation to keep track of old atom values (and I couldn't think of a decent API that would actually make such a feature usable...).

**Comment by marcloyal3** [comment] 2015-03-18 00:57
I guess what we need is an explanation of how Reagent works under the hood. Otherwise, it could at certain time feel like black magic with arbitrary rules (if we don't know what's going on.) 

Is it possible to describe how Reagent works under the hood in a few bullets, or how it works compared to naked React? A lot of us come to this not from React but from plain JS. So the less mysterious is Reagent's behavior (via documentation) the easier it will be for us to feel comfortable with it.

Does this request make any sense or do I have to just read the source code?

**Comment by marcloyal3** [comment] 2015-03-23 14:15
@holmsand 

I did some googled about React's shouldComponentUpdate and read somewhere that shouldComponentUpdate is called when either state or props change. Assuming that is correct , I think shouldComponentUpdate should be called in this case since state is changing. But in general, if I misunderstood, Reagent should follow React in terms of when the React callbacks are triggered unless it differs in its behavior compared to React in a consistent way. Otherwise, if it doesn't behave like React in this respect and doesn't have a consistent rule (or a consistent way in which it differs from React in this respect) then I think it's confusing to users coming from React and those of us coming from plain JS and looking to grasp how Reagent works.

**Comment by mike-thompson-day8** [comment] 2015-05-07 13:43
Dan has answered explaining why this is expected behaviour, so I'm wondering if this issue can be closed?

**Comment by mike-thompson-day8** [comment] 2015-08-24 02:18
I'm closing this issue.  As Dan previously indicated, this is expected behaviour.

**Closed by mike-thompson-day8** 2015-08-24 02:18 UTC
